name: App CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  task:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout files into runner
      uses: actions/checkout@v4
    
    - name: Install node js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Operations
      run: |
        npm ci
        touch .env
        PORT=${{secrets.PORT}} >> .env
        npm run dev
        npm run test
        