name: App CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout files into runner
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm ci

    - name: Run test suites
      run: npm run test

  start:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout files into runner
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm ci

    - name: Create env file
      run: |
        touch .env
        echo PORT=${{ secrets.PORT }}

    - name: Entrypoint
      run: npm run start 

  scan:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
    
    - name: Autobuild
      uses: github/codeql-action/autobuild@v3

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{matrix.language}}"
        