name: App CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout files into runner
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm ci

    - name: Run test suites
      run: npm run test

  start:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout files into runner
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm ci

    - name: Create env file
      run: |
        touch .env
        echo PORT=${{ secrets.PORT }}

    - name: Entrypoint
      run: npm run start 