name: App CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        run: |
          touch .env
          echo PORT=${{secrets.PORT}} >> .env
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
        
        