name: App CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout files into runner
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm ci

    - name: Run test suites
      run: npm run test

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout files into runner
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm ci

    - name: Run linter
      run: npx standard -v          